DROP FUNCTION "char"(integer);
DROP FUNCTION concat(text, text);
DROP FUNCTION insert(text, integer, integer, text);
DROP FUNCTION lcase(text);
DROP FUNCTION left(text, integer);
DROP FUNCTION locate(text, text);
DROP FUNCTION locate(text, text, integer);
DROP FUNCTION right(text, integer);
DROP FUNCTION space(integer);
DROP FUNCTION ucase(text);
DROP FUNCTION ceiling(numeric);
DROP FUNCTION log10(double precision);
DROP FUNCTION log10(numeric);
DROP FUNCTION power(double precision, double precision);
DROP FUNCTION power(numeric, numeric);
DROP FUNCTION rand();
DROP FUNCTION rand(double precision);
DROP FUNCTION truncate(numeric, integer);
DROP FUNCTION curdate();
DROP FUNCTION curtime();
DROP FUNCTION odbc_timestamp();
DROP FUNCTION dayname(timestamp);
DROP FUNCTION dayofmonth(timestamp);
DROP FUNCTION dayofweek(timestamp);
DROP FUNCTION dayofyear(timestamp);
DROP FUNCTION hour(timestamp);
DROP FUNCTION minute(timestamp);
DROP FUNCTION month(timestamp);
DROP FUNCTION monthname(timestamp);
DROP FUNCTION quarter(timestamp);
DROP FUNCTION second(timestamp);
DROP FUNCTION week(timestamp);
DROP FUNCTION year(timestamp);
DROP FUNCTION odbc_user();
DROP FUNCTION odbc_current_user();
DROP FUNCTION odbc_session_user();
